meson: fix generating pkg-config packages with internal dependencies
The 'requires' field does not work wit internal dependencies, use
'libraries' instead which does.

This fixes errors like the following:

ERROR:  requires argument not a string, library with pkgconfig-generated
file or pkgconfig-dependency object, got <InternalDependency null: True>

Requires Meson 0.49.