[test] Disable print tests
They crash for me due to some dogtail error

Traceback (most recent call last):
  File "./test6.py", line 21, in <module>
    click('Print to File', roleName='table cell', raw=True)
  File "/var/lib/python-support/python2.5/dogtail/procedural.py", line 299, in __call__
    Click.node.rawClick(button)
  File "/var/lib/python-support/python2.5/dogtail/tree.py", line 355, in rawClick
    extents = self.extents
  File "/var/lib/python-support/python2.5/dogtail/tree.py", line 523, in __getattr__
    return self.__component.getExtents()
  File "pyspi.pyx", line 747, in atspi.Component.getExtents
TypeError: an integer is required